[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
nebulon = "6UqkmQ2iCkf3acBB71DdXtVd49EyuaftMz8V3E74USbC"

[programs.localnet]
nebulon = "6UqkmQ2iCkf3acBB71DdXtVd49EyuaftMz8V3E74USbC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
